application/controllers/dashboard_controller.py
from flask import Blueprint, render_template, redirect, url_for, request, session, flash

dashboard_router = Blueprint("dashboard_router", __name__)

@dashboard_router.route("/", methods=['GET', 'POST'])
def dashboard_page():
    if "access_token" not in session:
        flash("you have to loggin first", "error")
        return redirect(url_for("auth_router.login_page"))

    user = session["user"]
    token = session["access_token"]
    return render_template("dashboard.html", token=token, user=user)

application/controllers/todo_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify, session
from application.services.todo_service import ToDoService

todo_router = Blueprint('todo_router', __name__)
todo_service = ToDoService()

@todo_router.route('/', methods=['GET', 'POST'])
def list_todo():
    if request.method == "GET":
        if "access_token" not in session:
            flash("you have to loggin first", "error")
            return redirect(url_for("auth_router.login_page"))

        user = session["user"]
        token = session["access_token"]
        data = todo_service.get_todo()
        return render_template("todo.html", data = data, user=user, token=token)
    if request.method == "POST":
        form_data = {
            "title": request.form.get("title"),
            "description": request.form.get("description")
        }
        response = todo_service.create_todo(form_data)
        flash(response.get("message", "Todo created successfully"), "success")
        return redirect(url_for("todo_router.list_todo"))

@todo_router.route("/edit/<string:todo_id>", methods=["GET", "POST"])
def update_todo(todo_id):
    user = session["user"]
    token = session["access_token"]

    if request.method == "POST":
        form_data = {
            "title": request.form.get("title"),
            "description": request.form.get("description")
        }
        response = todo_service.update_todo(todo_id, form_data)
        flash(response.get("message", "Todo updated successfully"), "success")
        return redirect(url_for("todo_router.list_todo"))

    data = todo_service.get_todo_id(todo_id)
    return render_template("list_todo.html", data=data, user=user, token=token)

application/templates/login.html
<!DOCTYPE html>
<html dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='assets/images/favicon.png') }}">
    <title> Login </title>
    <link href="{{ url_for('static', filename='dist/css/style.min.css') }}" rel="stylesheet">
</head>

<body>
    <div class="main-wrapper">
        <div class="preloader">
            <div class="lds-ripple">
                <div class="lds-pos"></div>
                <div class="lds-pos"></div>
            </div>
        </div>

        <div class="auth-wrapper d-flex no-block justify-content-center align-items-center" style="background:url() no-repeat center center;">
            <div class="auth-box">
                <div id="loginform">
                    <div class="logo">
                        <span class="db"><img src="{{ url_for('static', filename='assets/images/logo-icon.png') }}" alt="logo" /></span>
                        <h5 class="font-medium m-b-20">Sign In</h5>
                    </div>
                    <!-- Form -->
                    <div class="row">
                        <div class="col-12">
                            <form class="form-horizontal m-t-20" action="{{ url_for("auth_router.login_page") }}" method="post">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend"> <span class="input-group-text" id="basic-addon1"><i class="ti-user"></i></span> </div>
                                    <input type="text" name="username" class="form-control form-control-lg" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend"> <span class="input-group-text" id="basic-addon2"><i class="ti-pencil"></i></span> </div>
                                    <input type="password" name="password" class="form-control form-control-lg" placeholder="Password" aria-label="Password" aria-describedby="basic-addon1">
                                </div>
                                <div class="form-group text-center">
                                    <div class="col-xs-12 p-b-20"> <button class="btn btn-block btn-lg btn-info" type="submit"> Log In </button> </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{ url_for('static', filename='assets/libs/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/libs/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/libs/bootstrap/dist/js/bootstrap.min.js') }}"></script>

    <script>
        $('[data-toggle="tooltip"]').tooltip();
        $(".preloader").fadeOut();
        $('#to-recover').on("click", function() {
            $("#loginform").slideUp();
            $("#recoverform").fadeIn();
        });
    </script>
</body>

</html>

application/templates/todo.html
{% extends "layout/base.html" %}
{% block title %} Todo {% endblock %}

{% block content %}

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-5 align-self-center"> <h4 class="page-title"> Todo Managements </h4> </div>
        <div class="col-7 align-self-center">
            <div class="d-flex align-items-center justify-content-end">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"> <a href="#"> Todo </a> </li>
                        <li class="breadcrumb-item active" aria-current="page"> List </li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 grid-margin">
            <div class="card">
                <div class="card-title">
                    <div class="row">
                        <div class="col-md-12">
                            <button type="button" class="btn btn-outline-primary btn-sm btn-rounded waves-effect waves-light" onclick="openCreateTodo();">
                                <i class="fa fa-plus-circle"></i> New Todo
                            </button>
                        </div>
                    </div>

                    <div class="row d-none">
                        <div class="col-5 align-self-center"> <h4 class="page-title"> Todo List </h4> </div>
                        <div class="col-7 align-self-center">
                            <div class="d-flex align-items-center justify-content-end">  </div>
                        </div>
                    </div>

                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-sm">
                            <thead>
                                <tr>
                                    <th>Ref</th>
                                    <th>Title</th>
                                    <th>Description</th>
                                    <!-- <th>Created On</th> -->
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if data %}
                                    {% for task in data %}
                                        <tr>
                                            <td>{{ task['$id'] }}</td>
                                            <td>{{ task['title'] }}</td>
                                            <td>{{ task['description'] }}</td>
                                            <td>
                                                <button class="btn btn-sm btn-danger" onclick='deleteTodoRecord("{{ task.id }}")'><i class="fa fa-trash"></i></button>
                                                <button class="btn btn-sm btn-primary" data-id="{{ task['$id'] }}" onclick="updateTodoRecord('{{task.title}}', '{{task.description}}', this);"><i class="fa fa-edit"></i></button>

                                                <!-- <a href="{{ url_for('todo_router.update_todo', todo_id=task['$id']) }}" type="button" class="btn btn-info btn-sm btn-rounded waves-effect waves-light"
                                                    data-bs-toggle="modal" data-bs-target="#editModal-{{task['$id']}}">
                                                    <i class="fa fa-edit"></i>
                                                </a> -->

                                            </td>
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="10" style="text-align: center;">NO RECORD FOUND!!</td>
                                    </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Create Modal -->
<div class="modal fade" id="createTodoModal" tabindex="-1" role="dialog" aria-labelledby="create-todo" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="create-todo"> Create Todo Record </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <form action="{{ url_for('todo_router.list_todo') }}" method="post">
                <div class="modal-body">
                    <div class="row mb-1">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-label"> Title: <span class="text-danger">*</span> </label>
                                <input type="text" name="title" placeholder="please enter todo title" oninput="this.value = this.value.toUpperCase()" class="form-control">
                            </div>
                        </div>
                    </div>

                    <div class="row mb-1">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-label"> Description: <span class="text-danger">*</span> </label>
                                <textarea type="text" rows="3" name="description" placeholder="please enter todo description" oninput="this.value = this.value.toUpperCase()" class="form-control"></textarea>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-danger btn-sm" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary btn-sm"> Submit </button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- update modal -->
<div class="modal fade" id="editTodoModal" tabindex="-1" role="dialog" aria-labelledby="update-todo" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="update-todo"> Update Todo Record </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <form id="editForm" method="post">
                <div class="modal-body">
                    <div class="row mb-1">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-label"> Todo ID: <span class="text-danger">*</span> </label>
                                <input type="text" name="Id" id="todo_id" class="form-control" readonly>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-label"> Title: <span class="text-danger">*</span> </label>
                                <input type="text" name="title" id="todo_title" oninput="this.value = this.value.toUpperCase()" class="form-control">
                            </div>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-label"> Description: <span class="text-danger">*</span> </label>
                                <textarea type="text" rows="3" name="description" id="todo_description" oninput="this.value = this.value.toUpperCase()" class="form-control"></textarea>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-danger btn-sm" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary btn-sm"> Submit </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    const openCreateTodo = () => {
        $("#createTodoModal").modal("show");
    }
    const updateTodoRecord = (title, description, btn) => {
        const todoId = btn.dataset.id;
        document.getElementById("todo_id").value = todoId;
        document.getElementById("todo_title").value = title;
        document.getElementById("todo_description").value = description;

        let form = document.getElementById("editForm");
        const baseUrl = "{{ url_for('todo_router.update_todo', todo_id='__PLACEHOLDER__') }}";
        const actionUrl = baseUrl.replace('__PLACEHOLDER__', todoId);
        form.action =  actionUrl;

        $("#editTodoModal").modal("show");
    }
</script>

{% endblock %}