application/controllers/dashboard_controller.py
from flask import Blueprint, render_template, redirect, url_for, request, session, flash

dashboard_router = Blueprint("dashboard_router", __name__)

@dashboard_router.route("/", methods=['GET', 'POST'])
def dashboard_page():
    if "access_token" not in session:
        flash("you have to loggin first", "error")
        return redirect(url_for("auth_router.login_page"))

    user = session["user"]
    token = session["access_token"]
    return render_template("dashboard.html", token=token, user=user)

application/templates/layout/base.html
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='assets/images/favicon.png') }}">
    <title> {% block title %} {% endblock %} </title>
    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='assets/libs/chartist/dist/chartist.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='assets/extra-libs/c3/c3.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='assets/extra-libs/jvector/jquery-jvectormap-2.0.2.css') }}" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='dist/css/style.min.css') }}" rel="stylesheet">

    <style>
        .alert {
            animation: fadeOut 5s forwards;
        }

        @keyframes fadeOut {
            0% { opacity: 1; }
            80% { opacity: 1; }
            100% { opacity: 0; display: none; }
        }
    </style>
</head>

<body>
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <div id="main-wrapper">
        <header class="topbar">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header">
                    <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)">
                        <i class="ti-menu ti-close"></i>
                    </a>
                    <div class="navbar-brand">
                        <a href="{{ url_for('dashboard_router.dashboard_page') }}" class="logo">
                            <b class="logo-icon">
                                <img src="{{ url_for('static', filename='assets/images/logo-icon.png') }}" alt="homepage" class="dark-logo" />
                                <img src="{{ url_for('static', filename='assets/images/logo-light-icon.png') }}" alt="homepage" class="light-logo" />
                            </b>
                            <span class="logo-text">
                                <img src="{{ url_for('static', filename='assets/images/logo-text.png') }}" alt="homepage" class="dark-logo" />
                                <img src="{{ url_for('static', filename='assets/images/logo-light-text.png') }}" class="light-logo" alt="homepage" />
                            </span>
                        </a>
                        <a class="sidebartoggler d-none d-md-block" href="javascript:void(0)" data-sidebartype="mini-sidebar">
                            <i class="mdi mdi-toggle-switch mdi-toggle-switch-off font-20"></i>
                        </a>
                    </div>
                    <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="ti-more"></i>
                    </a>
                </div>
                <div class="navbar-collapse collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav float-left mr-auto">
                        <li class="nav-item search-box">
                            <a class="nav-link waves-effect waves-dark" href="javascript:void(0)">
                                <div class="d-flex align-items-center">
                                    <i class="mdi mdi-magnify font-20 mr-1"></i> <div class="ml-1 d-none d-sm-block"> <span>Search</span> </div>
                                </div>
                            </a>
                            <form class="app-search position-absolute">
                                <input type="text" class="form-control" placeholder="Search &amp; enter"> <a class="srh-btn"> <i class="ti-close"></i> </a>
                            </form>
                        </li>
                    </ul>
                    <ul class="navbar-nav float-right">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img src="{{ url_for('static', filename='assets/images/users/2.jpg') }}" alt="user" class="rounded-circle" width="40">
                                <span class="m-l-5 font-medium d-none d-sm-inline-block"> {{ user.get("full_name") }} <i class="mdi mdi-chevron-down"></i></span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
                                <span class="with-arrow"> <span class="bg-primary"></span> </span>
                                <div class="d-flex no-block align-items-center p-15 bg-primary text-white m-b-10">
                                    <div class=""> <img src="{{ url_for('static', filename='assets/images/users/2.jpg') }}" alt="user" class="rounded-circle" width="60"> </div>
                                    <div class="m-l-10">
                                        <h4 class="mb-0"> {{ user.get("full_name") }} </h4>
                                        <p class=" mb-0"> {{ user.get("email_address") }}  </p>
                                        <p class=" mb-0"> {{ user.get("phone_number") }}  </p>
                                    </div>
                                </div>
                                <a class="dropdown-item" href="javascript:void(0)"> <i class="ti-user m-r-5 m-l-5"></i> My Profile</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="javascript:void(0)"> <i class="fa fa-power-off m-r-5 m-l-5"></i> Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <aside class="left-sidebar">
            <div class="scroll-sidebar">
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark" href="{{ url_for('dashboard_router.dashboard_page') }}" aria-expanded="false"> <i class="mdi mdi-av-timer"></i> <span class="hide-menu"> Dashboard </span> </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"> <i class="mdi mdi-tune"></i> <span class="hide-menu"> Todo Managements </span> </a>
                            <ul aria-expanded="false" class="collapse  first-level">
                                <li class="sidebar-item"> <a href="{{ url_for('todo_router.list_todo') }}" class="sidebar-link"> <i class="mdi mdi-view-quilt"></i> <span class="hide-menu"> Todo </span> </a> </li>
                                <li class="sidebar-item"> <a href="#" class="sidebar-link"> <i class="mdi mdi-view-parallel"></i> <span class="hide-menu"> Comments </span> </a> </li>
                            </ul>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                                <i class="mdi mdi-crop-square"></i> <span class="hide-menu"> Reports </span>
                            </a>
                            <ul aria-expanded="false" class="collapse  first-level">
                                <li class="sidebar-item">
                                    <a href="#" class="sidebar-link"> <i class="mdi mdi-format-align-left"></i> <span class="hide-menu"> Task History </span> </a>
                                </li>
                                <li class="sidebar-item">
                                    <a href="#" class="sidebar-link"> <i class="mdi mdi-format-align-right"></i> <span class="hide-menu"> Comment History </span> </a>
                                </li>
                                <li class="sidebar-item">
                                    <a href="#" class="sidebar-link"> <i class="mdi mdi-format-float-left"></i> <span class="hide-menu"> Audit Trail </span> </a>
                                </li>
                            </ul>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                                <i class="mdi mdi-inbox"></i> <span class="hide-menu"> Configurations </span>
                            </a>
                            <ul aria-expanded="false" class="collapse  first-level">
                                <li class="sidebar-item">
                                    <a href="#" class="sidebar-link"> <i class="mdi mdi-email"></i> <span class="hide-menu"> User Management </span> </a>
                                </li>
                                <li class="sidebar-item">
                                    <a href="#" class="sidebar-link"> <i class="mdi mdi-email-alert"></i> <span class="hide-menu"> Role Management </span> </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <div class="page-wrapper">
            <div class="position-fixed top-0 end-0 p-3" style="z-index: 1100; width: 350px;">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} shadow fade show alert-fadeout" role="alert">
                                <div class="d-flex align-items-center">
                                    <div>
                                        <strong class="text-{{ category }}"> {{ category|capitalize }} </strong><br> {{ message }}
                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>

            {% block content %} {% endblock %}
            <footer class="footer text-center"> Copyright © <script>document.write(new Date().getFullYear())</script>. All Rights Reserved. Designed and Developed. </footer>
        </div>
    </div>

    <script src="{{ url_for('static', filename='assets/libs/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{{ url_for('static', filename='assets/libs/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/libs/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <!-- apps -->
    <script src="{{ url_for('static', filename='dist/js/app.min.js') }}"></script>
    <script src="{{ url_for('static', filename='dist/js/app.init.js') }}"></script>
    <script src="{{ url_for('static', filename='dist/js/app-style-switcher.js') }}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{{ url_for('static', filename='assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/extra-libs/sparkline/sparkline.js') }} "></script>
    <!--Wave Effects -->
    <script src="{{ url_for('static', filename='dist/js/waves.js') }}"></script>
    <!--Menu sidebar -->
    <script src="{{ url_for('static', filename='dist/js/sidebarmenu.js') }}"></script>
    <!--Custom JavaScript -->
    <script src="{{ url_for('static', filename='dist/js/custom.js') }}"></script>
    <!--This page JavaScript -->
    <!--c3 charts -->
    <script src="{{ url_for('static', filename='assets/extra-libs/c3/d3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/extra-libs/c3/c3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/extra-libs/jvector/jquery-jvectormap-2.0.2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/extra-libs/jvector/jquery-jvectormap-world-mill-en.js') }}"></script>
    <script src="{{ url_for('static', filename='dist/js/pages/dashboards/dashboard3.js') }}"></script>
</body>

</html>